### ISSUE TITLE
GELF TCP TLS authentication

### ISSUE THREAD

**Issue by CarlosLanderas** [serilog-contrib/serilog-sinks-graylog#70]
Hello. I've seen GELF TCP Inputs support TLS authentication. I need to expose a port to the internet to be able to receive logs from remote systems in a secure way. Does this library support TLS authentication when using TCP protocol?

Something like:

```csharp
_sslStream.AuthenticateAsClientAsync(_sslHost, certificate, true);
```

Thanks

**Comment by aqkhana2002** [comment]
or if that is not possible , can you allow us to Override method **TcpTransport.cs**
