### ISSUE TITLE
TcpTransport can we override ?

### ISSUE THREAD

**Issue by aqkhana2002** [serilog-contrib/serilog-sinks-graylog#76]
we are missing the certificate option in TcpTransport, I don't want to install the certificate on my machine, here is what I am doing in Graylog, but my company wants to use your package.

`        X509Certificate2 certificate2 =  new X509Certificate2("C:/Developer/Shared/test.pfx","");
                X509Certificate2Collection certificates = new X509Certificate2Collection(new X509Certificate2[] { certificate2});

                await _sslStream.AuthenticateAsClientAsync(_sslHost, certificates, SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12, false).ConfigureAwait(false);
                X509Certificate remoteCertificate = _sslStream.RemoteCertificate;`

**Comment by whir1** [comment]
You can try this in 3.0.1 version. To do this you should implement ITransport in GraylogSyncOptions and set transport type to Custom
