### ISSUE TITLE
Issue with update to version 3.0.0

### ISSUE THREAD

**Issue by GodEmperorOfTime** [serilog-contrib/serilog-sinks-graylog#93]
Hi,

I just encountered an issue after updating to `3.0.0` (from `2.3.0`): I don't see any records in Graylog server 😢

The same code with the previous version (`2.3.0`) of package works fine: [minimal repro](https://github.com/GodEmperorOfTime/GraylogIssueDemo)

Is it possible that the problem is TCP? Or am I missing something?

Program.cs:
```csharp
using Serilog;
var builder = WebApplication.CreateBuilder(args);
 // ..
builder.Host.UseSerilog((context, config) => {
  config.ReadFrom.Configuration(context.Configuration);
});
// ..
```
appsettings.json:

```json
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.Graylog" ],
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        //"Microsoft": "Warning" // Zdroj: https://nblumhardt.com/2016/07/serilog-2-minimumlevel-override/
      }
    },
    "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "Graylog",
        "Args": {
          "hostnameOrAddress": "192.168.144.226",
          "port": "12201",
          "transportType": "Tcp"
        }
      }
    ],
    "Properties": {
      "Application": "GraylogIssueDemo"
    }
  },
}

```

**Comment by jochenkluger** [comment]
Hi, 
same issue here. 
Using code to configure the graylog sink it works, using appsettings.json it does not work any more.

**Comment by whir1** [comment]
@GodEmperorOfTime 
It's very strange, one of these days I'll see why the configuration from the config stopped working
